<a href="https://colab.research.google.com/github/Amarsinh0/-PYTHON-NOTES/blob/main/scikit_learn_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import pandas and laod iris dataset **

In [19]:
import pandas as pd


In [20]:
iris=pd.read_csv("/content/Iris.csv")


In [21]:
from sklearn.datasets import load_iris

In [24]:
iris=load_iris()

In [25]:
x=iris.data

In [30]:
y=iris.target

In [32]:
feature_name =iris.feature_names

In [34]:
target_name=iris.target_names

In [36]:
print("feature_name:",feature_name)

feature_name: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [35]:
print("target_name:",target_name)

target_name: ['setosa' 'versicolor' 'virginica']


In [37]:
print('\nfirst 10 rows of x:\n',x[:10])


first 10 rows of x:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


# **spliting the dataset**


---





In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
print(x_train.shape)
print(x_test.shape)

In [41]:
print(y_train.shape)
print(y_test.shape)

(105,)
(45,)


# **train the model**

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
from sklearn import metrics

In [44]:
clf_knn=KNeighborsClassifier(n_neighbors=3)

In [ ]:
clf_knn.fit(x_train,y_train)

In [46]:
y_pred=clf_knn.predict(x_test)

finding the accuracy by comparing actual response value

In [47]:
print("accuracy:", metrics.accuracy_score(y_test,y_pred))

accuracy: 0.9777777777777777


## providing sample data and model we will prediction out of data

In [48]:
classifier_knn = KNeighborsClassifier()


In [50]:
sample=[[5,5,3,2],[2,4,3,5]]

In [53]:
preds=clf_knn.predict(sample)

In [61]:
pred_species=[iris.target_names[p]for p in preds]
print("prediction:",pred_species)

prediction: ['versicolor', 'virginica']


# model persistance - persist for future use







In [ ]:
from sklearn.externals import joblib

In [ ]:
joblib.dump(clf_knn,'iris_classifier_knn.joblib')

In [ ]:
joblib.load('iris_classifier_knn.joblib')

# **processing the data**

**binarisation**

In [72]:
import sklearn

In [73]:
from sklearn import datasets

In [ ]:
dir(datasets)

In [76]:
import numpy as np

In [ ]:
pip uninstall scipy

In [135]:
pip install scipy


In [137]:
pip install scikit-learn

In [136]:
from sklearn import preprocessing


In [99]:
input_data=np.array([[2.1,-1.9,5.5],
 [-1.5,2.4,3.5],
 [0.5,7.9,-5.6],
 [5.9,2.3,-5.8]])

In [103]:
data_binarized=preprocessing.Binarizer(threshold=0.5).transform(input_data)
print("\nBinarized data :\n",data_binarized)


Binarized data :
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 1. 0.]
 [1. 1. 0.]]


# **mean removal**

In [104]:
import numpy as np

In [105]:
from sklearn import preprocessing

In [106]:
input_data=np.array([[2.1,-1.9,5.5],
 [-1.5,2.4,3.5],
 [0.5,7.9,-5.6],
 [5.9,2.3,-5.8]])

# displaying the mean and the std deviation

In [111]:
print("mean",input_data.mean(axis=0))
print("std",input_data.std(axis=0))

mean [ 1.75   2.675 -0.6  ]
std [2.71431391 3.48021192 5.14927179]


# **removing mean and stand deviation**

In [113]:
data_scaled= preprocessing.scale(input_data)
print("mean_removed=",data_scaled.mean(axis=0))
print("standdeviation_removed=",data_scaled.std(axis=0))

mean_removed= [ 1.11022302e-16  1.07552856e-16 -5.55111512e-17]
standdeviation_removed= [1. 1. 1.]


# **scaling**

In [123]:
import numpy as np
from sklearn import preprocessing
input_data=np.array([[2.1,-1.9,5.5],
 [-1.5,2.4,3.5],
 [0.5,7.9,-5.6],
 [5.9,2.3,-5.8]])

In [125]:
data_scalar_minmax=preprocessing.MinMaxScaler(feature_range=(0,1))

In [126]:
data_scaled_minmax=data_scalar_minmax.fit_transform(input_data)


In [132]:
print("minmax scaled data :\n", data_scaled_minmax)

minmax scaled data :
 [[0.48648649 0.         1.        ]
 [0.         0.43877551 0.82300885]
 [0.27027027 1.         0.01769912]
 [1.         0.42857143 0.        ]]
